language: java
jdk:
  - oraclejdk8
sudo: false
branches:
  only:
    - master
env:
  global:
    - secure: "EL+cB87KI7FTCTt8nLDYu1Quvl8qsQRjBl3OsD+/DTb846OGXreuwv77nd/pd3inabIIcZIe5HQpae67Nfyxgdl2/+qVOCCZf980I+pG4W7qpYc9epyGZI/BgPzLFPknm0cKweu0mB0/t6ubTb0knFGJE+D9ny4926x3d5H94/4="
    - secure: "BA8Q3I1HiI0Tr0wEqWBpi5kXeOxE2OtDtNZUiIG3inJTedFAKTQ3d/g9au2mSqKiMIkPScQkO+mA4Fd16hFFtzFnec2AfoIhbTRwLgfC+/OjrNJK8AXw6XLorJiSV8yNI8qZYEHRyJtQ/W+09+UO7vtftUBPnNvf7fUmIqvwAzk="
script: 
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${SFUSER} -Dsf.password=${SFPWD} deploy || [ "${TRAVIS_PULL_REQUEST}" != "false" ]'
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${SFUSER} -Dsf.password=${SFPWD} deploy || [ "${TRAVIS_PULL_REQUEST}" = "false" ]'
